apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fw-transfer-singapore-prod
  namespace: argocd
spec:
  project: fw-transfer-project
  source:
    repoURL: git@github.com:kurorobot/k8s-fw-transfer.git
    targetRevision: HEAD
    path: kubernetes/overlays/singapore/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: singapore-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
