apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fw-transfer-tokyo-nonprod
  namespace: argocd
spec:
  project: fw-transfer-project
  source:
    repoURL: https://github.com/your-org/fw-transfer-app.git
    targetRevision: HEAD
    path: kubernetes/overlays/tokyo/nonprod
  destination:
    server: https://kubernetes.default.svc
    namespace: tokyo-nonprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
