apiVersion: apps/v1
kind: Deployment
metadata:
  name: fw-transfer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fw-transfer
  template:
    metadata:
      labels:
        app: fw-transfer
    spec:
      containers:
        - name: fw-transfer
          image: fw-transfer:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          env:
            - name: REGION
              value: 'tokyo' # デフォルト値
            - name: ENVIRONMENT
              value: 'prod' # デフォルト値
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '200m'
