apiVersion: apps/v1
kind: Deployment
metadata:
  name: fw-transfer-app
spec:
  template:
    spec:
      containers:
        - name: fw-transfer
          env:
            - name: REGION
              value: 'tokyo'
            - name: ENVIRONMENT
              value: 'prod'
